### ISSUE TITLE
LabronftLoader failed to inizialize

### ISSUE THREAD

**Issue by RadoslavaS** [dado93/pywearable#79]
Labfront changed the structure of the CSV files, with the keys `firstUnixTimestampInMs` and `lastUnixTimestampInMs` no longer available in the header of the CSV file, thus the main indexing function of LabfrontLoader must be rewritten.

**Comment by dado93** [comment]
I am currently working on the fix for this issue. With the new implementation, `pywearable.loader.LabfrontLoader` will index all the files in the project folder and store them in a `pd.DataFrame` with the following structure:

| fullId    | userId | labfrontId | metric                | fileName                     | firstTimestamp | lastTimestamp |
|-----------|--------|------------|-----------------------|------------------------------|----------------|---------------|
| user01_01 | user01 | 01         | garmin-connect-stress | garmin-connect-stress-file01 | 2024-01-01     | 2024-01-02    |
| user01_01 | user01 | 01         | garmin-connect-stress | garmin-connect-stress-file02 | 2024-01-02     | 2024-01-03    |

The `firstTimestamp` and `lastTimestamp` columns are populated based on the date present in the file names of Labfront according to the new naming convention.
